gpt2-small:
  size: "124M"
  config:
    emb_dim: 768
    n_layers: 12
    n_heads: 12

gpt2-medium:
  size: "355M"
  config:
    emb_dim: 1024
    n_layers: 24
    n_heads: 16

gpt2-large:
  size: "774M"
  config:
    emb_dim: 1280
    n_layers: 36
    n_heads: 20

gpt2-xl:
  size: "1558M"
  config:
    emb_dim: 1600
    n_layers: 48
    n_heads: 25

gpt2-small-gqa:
  size: "124M"
  config:
    emb_dim: 768
    n_layers: 12
    n_heads: 12
    num_kv_heads: 12
    enable_flash_att: True
    enable_gqa: True
